version: "3.7"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    tty: true
    restart: on-failure
    build: ./backend/
    volumes:
      - ./backend/src:/home/python/app/src
      - ./backend/assets:/home/python/app/assets
      - backend_env:/home/python/.local
      - backend_extensions:/home/python/.vscode-server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./.env
  frontend:
    tty: true
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/:/home/node/app
      - frontend_nodemodules:/home/node/app/node_modules
      - frontend_extensions:/home/node/.vscode-server
    ports:
      - "3000:3000"
    env_file: ./frontend/.env.local
    environment:
      HOME: /home/node
volumes:
  frontend_nodemodules:
  frontend_extensions:
  backend_env:
  backend_extensions:
  db-data:
